version: '2'

services:
    nginx:
        restart: always
        image: nginx:1.11.6-alpine
    postgres:
        restart: always
        image: postgres:9.5.6-alpine
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    server:
        restart: always
        build:
            context: .
            dockerfile: ./docker/server/Dockerfile
        volumes:
            - .:/app
