version: '2'

services:
    nginx:
        restart: always
        #image: nginx:1.12-alpine
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
    postgres:
        restart: always
        image: postgres:9.5.6-alpine
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        volumes:
            - .:/app
        environment:
            DATABASE_URL: postgres
            DATABASE_NAME: simple_tasks
            DATABASE_USER: tasks_user
            DATABASE_PASS: tasks_password
            DATABASE_PORT: 5432
            REDIS_URL: redis
            BROKER_URL: rabbitmq
            DJANGO_DEBUG: 'false'
